[[vinstance-component]]
== VINSTANCE Component

This specification defines the new "VINSTANCE" component, which is used to
represent just the differences between a generated instance, derived from the
master component, and the actual overridden instance that will be used instead of
the generated instance.

"VINSTANCE" components MUST only appear as sub-components within master
components (e.g., they can only appear as sub-components of components that
include at least one of either "RRULE" or "RDATE" properties).

Each "VINSTANCE" component MUST include a "RECURRENCE-ID" property with a value
that identifies the instance being overridden. Multiple "VINSTANCE" components
can appear within a single master component, but each MUST have a unique
"RECURRENCE-ID" property value. Unlike traditional overridden components,
"VINSTANCE" components MUST NOT include a "UID" property (the effective "UID" is
that of the master component enclosing the "VINSTANCE" component).

The iCalendar components and properties within a "VINSTANCE" component are
interpreted as follows:

. Any component appearing in "VINSTANCE" is treated as an addition or update to
the corresponding generated instance (see <<instance-components>>).

. Any property (excluding "RECURRENCE-ID" and "INSTANCE-DELETE") appearing in
"VINSTANCE" is treated as an addition or update to the corresponding generated
instance (see <<instance-properties>>).

. Any "INSTANCE-DELETE" property appearing in "VINSTANCE" indicates the removal
of a component or property from the corresponding generated instance (see
<<instance-delete>>)
