== iCalendar Extensions

[[vinstance]]
=== VINSTANCE Component

Component Name:: VINSTANCE

Purpose:: Provide components and properties that are used to indicate the
difference between a generated instance and an actual overridden instance.

Format Definition:: A "VINSTANCE" calendar component is defined by the following
notation:
+
[source%unnumbered]
----
vinstancec    = "BEGIN" ":" "VINSTANCE" CRLF
                  vinstanceprop component
                "END" ":" "VINSTANCE" CRLF
                ; Any sub-component allowed except for
                ; VINSTANCE itself. PATCH sub-components
                ; are used for incremental updates.

vinstanceprop = *(
                 ;
                 ; The following is REQUIRED,
                 ; but MUST NOT occur more than once.
                 ;
                 recurid /
                 ;
                 ; The following are OPTIONAL,
                 ; and MAY occur more than once.
                 ;
                 instancedelete / other-prop
                 ;
               )

other-prop  = ( iana-prop / x-prop )
----

Description:: This component is used to define an overridden instance of a
master component that can include changes to the generated instance, such as
component or property additions updates, or deletions. See
<<vinstance-component>> for details.

[[instancedelete]]
=== INSTANCE-DELETE Property

Property Name:: INSTANCE-DELETE

Purpose:: This property specifies a relative path identifying one or more
components or properties to be removed from a generated instance.

Value Type:: TEXT

Property Parameters:: IANA and nonstandard property parameters can be specified
on this property.

Conformance:: This property can be specified within a "VINSTANCE" component
only.

Description:: This property is used to match iCalendar components or properties
that will be deleted. The path value is always a relative path for only
immediate components and properties within the generated instance, and
interpreted as described in <<instance-delete>>.

Format Definition:: This property is defined by the following notation:
+
[source%unnumbered]
----
idelete       = "INSTANCE-DELETE ideleteparam ":" ideletepath CRLF

ideleteparam  = *(";" other-param)

ideletepath   = comp-path / prop-path
                  ; from Section XX of [draft-patch]
----

Example:: The following are examples of this property:
+
[source%unnumbered]
----
INSTANCE-DELETE:/VALARM[UID=1234]
INSTANCE-DELETE:#ATTENDEE[=mailto:cyrus@example.com]
----

[[instanceaction]]
=== INSTANCE-ACTION Property Parameter

Parameter Name:: INSTANCE-ACTION

Purpose:: To specify whether the property should be added or replaced.

Description:: This property parameter can be specified on properties contained
in a "VINSTANCE" component and MUST NOT be specified on properties outside of a
"VINSTANCE" component. This property parameter specifies whether the associated
property should be added to the generated instance or should replace existing
properties in the generated instance. In the latter case, the property parameter
also specifies how to match existing properties. The processing of this property
parameter is described in <<instance-properties>>.

Format Definition:: This parameter is defined by the following notation:
+
[source%unnumbered]
----
iactionparam    = "INSTANCE-ACTION" "="
                    iactioncreate /
                    iactionupdate /
                    iactionbyname /
                    iactionbyparam /
                    iana-token /     ; IANA registered value
                    x-name           ; Experimental value

iactioncreate   = "CREATE"
                ; Always add property to the generated instance.

iactionupdate   = "UPDATE" *["~" param-name]
                ; Always update or remove parameters on properties
                ; with the same name and value in the generated
                ; instance.

iactionbyname   = "BYNAME"
                ; Always replace properties with the same name
                ; in the generated instance.
                ; This value is the default and MAY be omitted.

iactionbyparam  = DQUOTE "BYPARAM" param-match   DQUOTE
                ; Always replace properties with the same name
                ; and parameter name/value in the generated
                ; instance.
----

Examples:: The following are examples of this property parameter:
+
[source%unnumbered]
----
ATTENDEE;INSTANCE-ACTION=UPDATE~RSVP;PARTSTAT=NEEDS-ACTION:
 mailto:cyrus@example.com
DESCRIPTION;INSTANCE-ACTION="BYPARAM@LANGUAGE=en_GB";LANGUAGE=en_US:
 Meeting to discuss VINSTANCE
----
