== IANA Considerations

=== Component Registrations

This document defines the following new iCalendar components to be added to the
registry defined in <<RFC5545,section=8.3.1>>:

[cols="^,^,^"]
|===
|Component |Status |Reference

|VINSTANCE |Current |RFCXXXX, <<vinstance>>
|===

=== Property Registrations

This document defines the following new iCalendar properties to be added to the
registry defined in <<RFC5545,section=8.3.2>>:

[cols="^,^,^"]
|===
|Property |Status |Reference

|INSTANCE-DELETE |Current |RFCXXXX, <<instancedelete>>
|===

=== Parameter Registrations

This document defines the following new iCalendar parameters to be added to the
registry defined in <<RFC5545,section=8.3.3>>:

[cols="^,^,^"]
|===
|Property |Status |Reference

|INSTANCE-ACTION |Current |RFCXXXX, <<instanceaction>>
|===

=== Parameter Value Registry

A new IANA registry for iCalendar elements has been added. Additional codes MAY be
used, provided the process described in <<RFC5545,section=8.2.1>> is used to
register them, using the template in <<RFC5545,section=8.2.6>>.

==== Instance Action Registry

The following table has been used to initialize the Instance Action Registry:

[cols="^,^,^"]
|===
|Instance Action |Status |Reference

|CREATE |Current |RFCXXXX, <<instanceaction>>
|UPDATE |Current |RFCXXXX, <<instanceaction>>
|BYNAME |Current |RFCXXXX, <<instanceaction>>
|BYPARAM |Current |RFCXXXX, <<instanceaction>>
|===
